name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      CS_ACCESS_TOKEN: ${{ secrets.CS_ACCESS_TOKEN }}
      CODESCENE_CLI_SHA256: ${{ vars.CODESCENE_CLI_SHA256 }}
    steps:
      - uses: actions/checkout@v4
      - uses: leynos/shared-actions/.github/actions/setup-rust@732d248978b5d9b7521ce8a2b34b9f3eaf58a8e8
      - name: Format
        run: make check-fmt
      - name: Lint
        run: make lint
      - id: generate-coverage
        uses: leynos/shared-actions/.github/actions/generate-coverage@732d248978b5d9b7521ce8a2b34b9f3eaf58a8e8
        with:
          output-path: lcov.info
          format: lcov
      - name: Upload coverage data to CodeScene
        env:
          CS_ACCESS_TOKEN: ${{ secrets.CS_ACCESS_TOKEN }}
        if: ${{ env.CS_ACCESS_TOKEN != '' }}
        uses: leynos/shared-actions/.github/actions/upload-codescene-coverage@v1.2.1
        with:
          format: lcov
          access-token: ${{ env.CS_ACCESS_TOKEN }}
          installer-checksum: ${{ vars.CODESCENE_CLI_SHA256 }}
