name: Release Binary

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: x86_64
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: linux
            arch: aarch64
            target: aarch64-unknown-linux-gnu
            ext: ""
          - os: windows
            arch: x86_64
            target: x86_64-pc-windows-msvc
            ext: ".exe"
          - os: windows
            arch: aarch64
            target: aarch64-pc-windows-msvc
            ext: ".exe"
          - os: macos
            arch: x86_64
            target: x86_64-apple-darwin
            ext: ""
          - os: macos
            arch: aarch64
            target: aarch64-apple-darwin
            ext: ""
          - os: freebsd
            arch: x86_64
            target: x86_64-unknown-freebsd
            ext: ""
          - os: freebsd
            arch: aarch64
            target: aarch64-unknown-freebsd
            ext: ""
          - os: openbsd
            arch: x86_64
            target: x86_64-unknown-openbsd
            ext: ""
          - os: openbsd
            arch: aarch64
            target: aarch64-unknown-openbsd
            ext: ""
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross --tag v0.2.1
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build release binary
        run: cross build --release --target ${{ matrix.target }}
      - name: Prepare artifact
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/${{ env.REPO_NAME }}${{ matrix.ext }} \
            artifacts/${{ env.REPO_NAME }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPO_NAME }}-${{ matrix.os }}-${{ matrix.arch }}
          path: artifacts/${{ env.REPO_NAME }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: |
          for file in artifacts/${{ env.REPO_NAME }}-*; do
            gh release upload "${{ github.ref_name }}" "$file"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
